version: '3.8'

services:
  users-api:
    container_name: holidayextra-users
    hostname: users
    networks:
      - holidayextra
    volumes:
      - ../:/service
    build:
      context: ../
      target: development
      dockerfile: src/Dockerfile
    entrypoint: ["yarn", "start:dev"]
    ports:
      - 3000:3000
    tty: true
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: holidayextra-mongodb
    hostname: mongodb
    command: --serviceExecutor adaptive
    volumes:
      - ./volumes/mongo:/data/db
    networks:
      - holidayextra
    ports:
      - 27017:27017
    logging:
      driver: none

networks:
  holidayextra: